docusaurus.config.js
support facebook, twitter, linkedin, discord
=> fix: open graph meta

docusaurus.config.js
=> fix: open graph image https url

docusaurus.config.js
=> fix: open graph description

blog/2023-02-17-plugins.md, blog/authors.yml
A blog post that tells the tale of a crazy heroic platform engineer named Susan.
=> blog: wing your way to better infrastructure with plugins

docusaurus.config.js, src/css/custom.css
=> chore: font weight update and remove breadcrumbs

docusaurus.config.js
=> feat: remove stack overflow link from footer

.github/workflows/reindex.yml
=> fix: match vercel target_url to our main vercel site url

blog/2022-12-28-magazine-001.md, blog/2023-3-5-magazine-002.md, docusaurus.config.js
=> fix: broken links

scripts/updateDocs.ts
=> chore: fix docs auto update

.github/workflows/update-docs.yml
=> chore: update docs workflow

docusaurus.config.js
=> fix: edit url is not working

docusaurus.config.js
=> fix(docs): broken link after domain merge

docusaurus.config.js, package-lock.json, package.json
=> chore: add node polyfill to support buffer

docusaurus.config.js, versioned_docs/version-latest/src/components/CodeComparison.jsx, versioned_docs/version-latest/src/examples/function-upload-to-bucket/platforms.js, versioned_docs/version-latest/src/examples/function-upload-to-bucket/wing.js
=> fix: custom components assets

docusaurus.config.js
resolves: https://github.com/winglang/wing/issues/3304
=> fix: footer light mode

contributing_versioned_docs/version-latest/02-maintainers/050-operations.md, docusaurus.config.js, src/theme/CodeBlock/Content/String.js, versioned_docs/version-latest/999-faq/004-what-pains-wing-solves.md, versioned_docs/version-latest/999-faq/040-alternatives/041-terraform-vs-wing.md, versioned_docs/version-latest/999-faq/040-alternatives/042-pulumi-vs-wing.md, versioned_docs/version-latest/999-faq/040-alternatives/043-awscdk-vs-wing.md, versioned_docs/version-latest/999-faq/040-alternatives/044-cdktf-vs-wing.md, versioned_docs/version-latest/999-faq/040-alternatives/047-darklang-vs-wing.md
=> fix: changing play link

blog/2022-11-23-manifesto.md, blog/authors.yml, docusaurus.config.js
feat(docs): convert monada to wing cloud
Updates the Wing docs. See details in [workflow run].
[Workflow Run]:
https://github.com/winglang/docsite/actions/runs/5550648617
------
*Automatically created via the "update-docs" workflow*
Signed-off-by: monabot <monabot@monada.co>
=> feat(docs): convert monada to wing cloud

blog/2023-01-30-wingly-wing-project-management-process.md, blog/2023-02-09-wingly-onboarding-process.md, blog/2023-04-07-wingly-compiling-wing-on-different-clouds.md, blog/2023-04-07-wingly-same-object-different-interfaces-for-preflight-and-inflight.md, blog/2023-05-25-wingly-testing-app-on-the-cloud.md, blog/2023-06-05-wingly-built-in-syntax.md, blog/2023-06-15-wingly-testing-with-winglang.md, blog/2023-06-16-wingly-api-endpoint.md, blog/2023-06-29-wingly-counter-resource.md, blog/2023-07-13-wingly-new-utility-functions.md, blog/2023-07-13-wingly-winglang-vscode.md, blog/2023-07-16-wingly-inflight-classes.md, blog/authors.yml
Add video posts to the Wing blog.
=> Wingly in blog

src/components/NavbarItems/GithubButton.tsx
=> fix: site crashes on gh starts count error

src/components/NavbarItems/GithubButton.tsx
=> fix: round up or down gh stars count

docusaurus.config.js
=> fix: edit redirects to main branch

blog/2023-08-10-wingly-introducing-wing-cloud.md
=> Video: Goodbye Monada - Hello Wing Cloud

src/css/custom.css
=> feat: improve blog style

blog/2023-09-25-constructs-api-design.md, blog/2023-09-25-constructs-methods.md
=> feat: Avoiding mutability pitfalls in constructs-based API design

src/css/custom.css
=> feat: increase body font weight

blog/2023-09-21-adam-jacob-summary.md
I think this typo is the cause of the current build failure
=> fix: author typo

blog/2023-09-25-constructs-api-design.md
=> fix: constructs api design open graph image

docusaurus.config.js
Resolves https://github.com/winglang/wing/issues/5014
=> fix: missing favicon

blog/2023-12-04-magazine-005.md
=> chore: convert inflight magazine to code

docusaurus.config.js
=> fix: redirect and canonical urls

docusaurus.config.js
=> fix: redirects

blog/2024-01-04-platforms-building-part1.md
My initial pass at writing a guide on building Custom Wing Platforms
=> blog: Crafting Custom Platforms in a Cloudy World

blog/2024-1-30-hello-winglang-hexagon.md
=> docs: fix typos in hello-winglang-hexagon blog

src/css/custom.css
=> feat: increase header tabs font size

docusaurus.config.js, src/theme/BlogListPage/Author/index.js, src/theme/BlogListPage/Author/styles.module.css, src/theme/BlogListPage/ListItem/index.js, src/theme/BlogListPage/ListItem/styles.module.css, src/theme/BlogListPage/index.js, src/theme/BlogListPage/styles.module.css
=> feat: create a blogs entry page with thumbed intros

blog/2023-07-18-wing-cloud-launch.md
=> fix: broken link

blog/2024-1-30-hello-winglang-hexagon.md
=> docs: Add canonical link to hello-winglang-hexagon blog

blog/2024-03-12-crud-rest-api.md
=> chore(docs): Update the title of the crud-rest-api article

blog/2024-02-15-private-api-gateways.md
=> feat(docs): adding back the generic article about Private API Gateway

blog/2024-04-10-in-search-for-winglang-middleware.md
=> chore(docs): add Asher's article to the blog section

blog/2024-04-19-magazine-009.md
- Changed order to sections to match TOC
- Fixed some formatting issue in one of the links
=> chore: tweaks to inflight magazine 9

blog/2024-04-19-magazine-009.md
=> fix: inflight magazine 9 blog image

blog/2024-05-07-in-search-for-winglang-middleware-part-two.md
=> chore(docs): Update article title

blog/2024-05-07-in-search-for-winglang-middleware-part-two.md
=> chore(docs): add spacing for the sub title

blog/2024-05-16-chatgpt-client-with-nextjs-and-wing.md
=> chore(docs): correct typos in the article

blog/2024-05-29-qa-bot-for-your-docs-with-langchain.md
=> chore(docs): Update the blog title

blog/2024-05-29-qa-bot-for-your-docs-with-langchain.md
=> chore(docs): Update blog title

blog/2024-05-29-qa-bot-for-your-docs-with-langchain.md
=> chore(docs): Fix typos in the blog

blog/2024-05-29-qa-bot-for-your-docs-with-langchain.md
=> chore(docs): Revise the QA bot article with added Langchain processing code

blog/2024-05-29-qa-bot-for-your-docs-with-langchain.md
=> chore(docs): Update the secrets portion of the blog

.github/workflows/build.yml, .github/workflows/reindex.yml, .github/workflows/update-docs.yml
Upgrades actions (including upgrading node to v20) in the hopes of fixing the CI jobs.
=> chore: upgrade github actions

blog/2024-05-16-chatgpt-client-with-nextjs-and-wing.md, blog/2024-05-29-qa-bot-for-your-docs-with-langchain.md, versioned_docs/version-latest/01-start-here/02-getting-started.md, versioned_docs/version-latest/08-guides/03-react-vite-websockets.md
=> chore(docs): fixing version reference

src/components/PageTemplates/Example.tsx, src/css/custom.css
Small CSS fix for the docs website.
=> fix(docs): fixed styling for docs

src/css/custom.css
=> fix(docs): fixed navbar overlap issues

docusaurus.config.js, src/css/custom.css
Fix for https://github.com/winglang/wing/issues/6998
=> chore(docs): reduced the number of links in nav

docusaurus.config.js, src/components/Landing/ContactForm.tsx, src/components/Landing/ContactUs.tsx, src/components/Landing/Features.tsx, src/css/custom.css, src/pages/community.tsx, src/pages/contact.tsx
Added new community page and contact us page, so we can turn off the proxy and go live with landing page.
=> feat(docs): added new community and contact pages

src/theme/BlogListPage/ListItem/index.js
Added the dates to the blog posts
=> fix(docs): added dates to blog posts
